### PR TITLE
Various performance improvements and an out-of-memory crash during recording fix

### PR DESCRIPTION
**Pull request by leszekm1**
Leave a comment

### CODE REVIEW

**Comment by leszekm1** [comment]
Hi,
CameraWindow.cs: 
- The system wide inter-process global event is very cpu intensive.  Profiling the app under VC2017 shows it using 9% of the cpu NOT counting the 5ms of wait.  This, and the 5ms of wait while might slow down CPU usage but does reduce your recorded FPS as the recording thread will not be able to process all incoming frames and they will be discarded by the reading thread from the buffer instead.  The boolean flag instead gives you no CPU overhead and I bet you get much more frames recorded (yes with a higher CPU usage but you'll drop less frames on recording.)  To ensure however that the recording thread does play nice I added a thread.yield in my latest commit if there are no frames available in the buffer to record. (see the latest commit changes)
- For the async queuing make sure you pick up all my changes - the enqueuing should happen at the end of the reading loop so that only the recording thread will touch those once they are handed of to the helper thread to be put on the queue.
MediaStream.cs:
- The current code base defines abort as a Boolean and you do have a spin wait of 20ms in the reading loop in the current master branch.  That artificially lowers incoming FPS for no apparent reason. You're not "saving" CPU since ffmpeg av_read_frame() is a blocking call so that will save your CPU if there are no frames to be read.
TwoFramesDifferenceDetector.cs:
- Those changes should save you about 20% or so overall CPU utilization.  Per VC2017 profiler my changes made the CPU utilization of the detector go from 40% to 10% of the overall usage for the app making the JPEG compression the biggest culprit.
- Since the detector is now purely a bitwise algorithm it only has 8 possible levels of comparisons so 15 would really map to 8 hence 16.

**Comment by ispysoftware** [comment]
Nice one on improving the CPU usage but i'm having some major issues with
the changes to the camerawindow.cs code.

I merged all your changes, it crashed on the first frame with the same
execption as before. I disabled the async buffer write and it ran but
generated errors in the log file:

Error 11:38:12 AM Camera 4: A generic error occurred in GDI+.: at
System.Drawing.Image.Save(String filename, ImageCodecInfo encoder,
EncoderParameters encoderParams) at
iSpyApplication.Controls.CameraWindow.Record() in
D:\Projects\iSpy\iSpy\Controls\CameraWindow.cs:line 3238
Error 11:38:16 AM Camera 4: Error while writing video frame (-542398533) (
at iSpyApplication.Realtime.MediaWriter.WriteFrame(Bitmap frame, Int32
level, Int64 msOffset) in
D:\Projects\iSpy\iSpy\Realtime\MediaWriter.cs:line 456 at
iSpyApplication.Realtime.MediaWriter.WriteFrame(Bitmap frame, Int64
msOffset) in D:\Projects\iSpy\iSpy\Realtime\MediaWriter.cs:line 376 at
iSpyApplication.Controls.CameraWindow.WriteFrame(FrameAction fa, DateTime
recordingStart, Int64& lastvideopts, Double& maxAlarm, Nullable`1&
peakFrame, Int64& lastaudiopts) in
D:\Projects\iSpy\iSpy\Controls\CameraWindow.cs:line 3417 at
iSpyApplication.Controls.CameraWindow.Record() in
D:\Projects\iSpy\iSpy\Controls\CameraWindow.cs:line 3192)

**Comment by leszekm1** [comment]
I see the issue.  It exists in the original code but is probably more prominent with my changes.  In the original (current master) code take a look at lines 3404 and 3425.  On 3404:
 peakFrame = fa;
you set the peakFrame but on 3425:
fa.Nullify();
you delete the buffer under it no?
Let me work on fixing that.

**Comment by leszekm1** [comment]
Ok, take a look at the latest commit.  It should fix the issue you're having.

**Comment by ispysoftware** [comment]
with a standard network camera it's working fine. With a local high
resolution usb camera i'm still getting "Parameter is not valid" exceptions
at

frame.Save(ms, MainForm.Encoder, MainForm.EncoderParams);

in FrameAction

I think this is because the async method is causing the bitmap to be
disposed of before the constructor of the frameaction completes.

.. try it on a high resolution USB camera and see if you can reproduce it.

**Comment by leszekm1** [comment]
Ok, will look tomorrow into it.  Which USB camera are you using?

**Comment by ispysoftware** [comment]
I've got a realsense camera, it's running at 1920x1080 @ 30 fps

**Comment by leszekm1** [comment]
You are absolutely right.  The various sources wrap the call to the delegate with a "using bitmap" statement and start releasing the bitmap as soon as the delegate completes.  The latest commit creates a copy of the bitmap before passing it to the async delegate.  On my USB camera this fixes the issue.  Let me know if it works on yours.

**Comment by ispysoftware** [comment]
Clone creates a shallow copy of the bitmap - the bitmap data is still
stored in the same memory location - so if it is disposed by the "using"
statement before the constructor of the frameaction runs there is a (very
small) chance that the data will be corrupted by something else before the
constructor is run.

Doing a complete copy is very expensive and i can't see another way to make
this async without introducing potential new exception scenarios.

Also i'm not clear on why this should be async - are there any clear
benefits to it?

**Comment by leszekm1** [comment]
The only benefit is that you can increase your FPS if you have more cores than cameras.  Other than this case there is no benefit to make it async.  Leave it sync then.

**Comment by leszekm1** [comment]
Although according to this:
http://stackoverflow.com/questions/12709360/whats-the-difference-between-bitmap-clone-and-new-bitmapbitmap
the "using" statement should not affect the clone and my code should work.

**Comment by ispysoftware** [comment]
Yeah possibly, i'll do some testing.

**Comment by leszekm1** [comment]
done

**Pull request closed without merging**
