### PR TITLE
Cut garbage and update .gitignore

### PR DESCRIPTION
**Pull request by mirh**
It wasn't [that](https://git-scm.com/docs/gitignore) hard after all. 
I still miss redist to exclude though, since I haven't understood if "[DownloadUrl](http://wixtoolset.org/documentation/manual/v3/xsd/wix/exepackage.html)" means that you can delete local copy because it will be downloaded at build time or what. 

NOTE: I wouldn't like to sound aggressive or something, but before any further coding it would be better if we could figure this out. 
Once even redist crap gets out, we should clean the repository history from half a GB of aforementioned garbage. 

I'm not a git guru but some tinkering with [git rebase](https://git-scm.com/book/it/v2/Git-Tools-Rewriting-History) -i should do the trick. 
Of course better if you check three times before force pushing. 

EDIT: tested locally, and it seems you should just need to reword 7d709eb9d4aa2a1f44b888a270a6a2a535ef1eb0, then [fixup](https://help.github.com/articles/about-git-rebase/) every following commit
EDIT2: then of course (from the single massive commit that will result) you may want to split/edit it, but this is your call
EDIT3: [this](https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/) could also help?

### CODE REVIEW

**Comment by mirh** [comment]
Oh, also stuff in DLLS folder seems worth a trim.

**Comment by mirh** [comment]
Also deleted binaries in FFmpeg.AutoGen (and added them to .gitignore of course). 
Wouldn't it be neater to link [it](https://github.com/Ruslan-B/FFmpeg.AutoGen) via submodule?

Dlls in Plugins folder look suspicious too. 

P.S. if you are reading this from e-mails I have edited quite a lot of stuff above

**Comment by ispysoftware** [comment]
Hello the ffmpeg.autogen project required a few changes to make it work,
which is why it's copied here. I've sent those changes to the author, if he
merges them in then we're good.

**Comment by mirh** [comment]
Cool, wonderful. 
I believe you confused "review changes" with "pull changes" though 😆

**Comment by ispysoftware** [comment]
Yeah i'm still getting to grips with github - it's quite confusing.

**Comment by mirh** [comment]
Wtf?
Man, revert last change. 
You should have merged THIS pull request only (web interface is best probably for this). 
Not.. AGAIN your local screwed repo.

**Comment by ispysoftware** [comment]
i'll  download the git and start afresh tomorrow.

**Comment by mirh** [comment]
You tweaked .gitignore.. *Fine*.
But you still miss all binaries in Wix, FFmpeg and (possibly) DLLS folders.

**Comment by ispysoftware** [comment]
Yeah I'm not sure why the git ignore isn't working. Any ideas?

**Comment by mirh** [comment]
Simply delete those files, then commit. 
"Ignoring" here means that if it's already there you don't touch it.

**Comment by ispysoftware** [comment]
Yeah according to visual studio they aren't checked in.. they don't exist
on my hard drive. Something gone wrong. I'll sort it out.

**Comment by mirh** [comment]
Ok, we had progresses in fact. 
Unfortunately you have no *issues*, so I'll keep reporting here. 

Speaking of gitignore, you should: remove the Bootstrap## stuff (it's already included by ** above) and put a / after [Bb]in

Then, you should delete all `.bak` and `.DotSettings` files. 
And last, but not least, I'm still highly doubtful on your DLLS folder. 1) It's not like you couldn't retweak the readme to work like once 2) Shipping 80MB of binaries in sources is nuts 3) I'm not even sure you are allowed to ship microsoft vs redist dlls

**Comment by mirh** [comment]
Before doomsday could you please cut clutter from DLLS folder?
I don't do it myself because I'm not sure why you (the guy that should care mostly) dropped the previous "put dlls here" solution and/or you couldn't prefer git LFS/submodules.

**Comment by CollinChaffin** [comment]
@ispysoftware Hey Sean don't feel bad, after many years I still find certain aspects of working with Git very counter-intuitive too.  It is too bad that attempting to fix the repo killed all the open issues.....you are aware of that I assume.  In the end, likthie @mirh I too would recommend starting with only the web interface, don't worry about the gitignore at all, and worst case scenario, since you've kind of reset most of the repo now, anyway, what I have done in these cases is to actually stage the LOCAL exactly how you want to rebase to, and then do just that - reset and rebase the repo.

I would normally warn with such a big product and this much history NOT to do it since it would wipe out your history and issues, but since that's already been done let me know if you need help with the command/procedure to do a full reset/rebase and basically re-init from a certain point and I'll be happy to help!

**Comment by mirh** [comment]
I didn't actually recommend to dupe the repo. Just rebase & clean (not necessarily in this order). 
Though, if we still have like 40MB of clutter (DLLS), I'm not even trying then. 

Also, redist folder may count (but I'm not sure how Wix works, so..)

> I too would recommend starting with only the web interfac

The only thing I recommended was to enable issues tab, so I don't need to find a bug every time I want to raise a point with dev. 
Aside of that, honestly it's not like you could do true development from web interface.

**Comment by CollinChaffin** [comment]
Correct we are saying the same thing just a communication breakdown I also agree a simple rebase and clean and enabling the issues tab again is probably pretty critical at this point (and by far the simplest option).  I just did not see those commands/procedure listed and did not know if he knew or needed help since Github can get a bit finicky when rebasing and using the GUI.

**Comment by ispysoftware** [comment]
The main reason the issues tab was disabled is because it filled up with
people saying "how can i get my camera to work?" and  sorting through it
was taking too much time. Actual properly documented code issues accounted
for less than 1% of the reported issues.

I'll switch issues back on again.. see how we go.

I'm a total noob when it comes to Git so yes any help would be great.

**Comment by CollinChaffin** [comment]
Hey Sean,

So just to be clear on the same page with @mirh too I did not want to step on any toes - is the desired result here is to get one totally cleaned perfect local directory structure on your system, and then because of this buildup/mess wipe all prior commits and the big key also the prior messy commit history (which in most instructions is very difficult to actually get rid of) and rebase/init from scratch with his new cleaned up structure?

I ask because we do want to verify that any forks or pulls based on prior commits will wind up obviously orphaned completely but it doesn't sound like that is an issue at all.  As long as you're okay with that (and I'm guessing you are since it's gotten pretty messy) and you DO want to do away with prior commit history - then here's my procedure I've used often:

- [ ] Using Git shell CD to your ispy code dir and then do this for a  final checkout in current state:
			`git checkout --orphan latest_branch`

- [ ] Now stage and cleanup the ispy code folder structure exactly how you want to reinit and once the local copy is perfect issue this command:
			`git add -A`
- [ ] Commit the changes using this comment (or change to your liking)
			`git commit -am "Initial Commit"`
- [ ] DANGER WILL ROBINSON - this will now DELETE the existing messy branch online
			`git branch -D master`
- [ ] This command is the trick to then rename the current temp orphaned branch as the new master:
			`git branch -m master`
- [ ] Issue the typical push command always required to push these changes to the online repo:
			`git push -f origin master`

This is the procedure I usually follow if I have a seriously borked repo that I simply want to reinit using a perfected local copy, while deleting all prior commit history completely (most other procedures will NOT remove the FULL history) and leave me with a fresh, single commit rebased repo.

Hope this helps.  If you're interested in adding me as a contributor at some point that would be great now that the codebase is getting cleaned up with the latest build and things with FFMPEG sorted out I am hoping to have some time to begin hopefully adding some code improvements too.

-Collin

**Comment by mirh** [comment]
> The main reason the issues tab was disabled is because it filled up with people saying "how can i get my camera to work?" 

Oh jeez. I can see that then.. Though, were they really chatroom-spam-like levels that you could hardly keep up with them?

> I ask because we do want to verify that any forks or pulls based on prior commits will wind up obviously orphaned completely but it doesn't sound like that is an issue at all. 

Putting aside this would be like giving the middle finger to @yablacky, check my EDIT n°1 and 3 above. You rebase over the monstrous commits, and if garbage is still left behind then you filter delete it. 

Of course it wouldn't be bad to try this on a test repo before doing anything.

**Comment by CollinChaffin** [comment]
That's a good idea feel free to take my steps above and create a test repo, do a few commits adding some files first and then follow my direction and if you follow it, you will wind up with a repo that has a single commit and successfully has zero commit history and perfectly reflects your local file layout.  If you do other rebase methods it will leave behind all the messy history which is why I always recommend to do a full history reset the above is used.

**Comment by mirh** [comment]
>  If you do other rebase methods it will leave behind all the messy history

In rebase, you can squash/fixup just the relevant messy parts.

**Comment by ispysoftware** [comment]
Hi Colin, I tried doing this, got

D:\Projects\iSpy\iSpy>git push -f origin master
Username for 'https://github.com': ispysoftware
Password for 'https://ispysoftware@github.com':
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/ispysoftware/iSpy.git
'


D:\Projects\iSpy\iSpy>git show-ref
62d244de430fac044a63d79bcdc2eafd1b4c602d refs/heads/latest_branch
eec0a3d9aabbc43bd3b5916890321a842375e67f refs/heads/pr/11
283a5e9315833e0f0540dabeef4f014bde746aa8 refs/remotes/origin/master



- any ideas?

**Comment by profporridge** [comment]
Please do not follow this advice. No repo is beyond repair, and this one is
not that bad. Besides, you could always create a new project if you want to
start over.

**Comment by mirh** [comment]
I agree with the last comment. 
Please just put to rest once and for all the DLLS (and wix-redist perhaps) question, as you better like and prefer, then (given I can afford the luxury to just screw my own test repo) I'll take care of the remainder commands to clean up.

**Comment by ispysoftware** [comment]
Sorry what do you want me to do with the DLLs? The ffmpeg dlls are from
zeranoe (non github) and the others are either proprietary or builds with
minor modifications.

**Comment by mirh** [comment]
Putting aside the philosophical "binaries in sources are bad", more pragmatically it seems insane having 121MB of sources, 97 of which are "~~useless~~ incidental stuff". Let alone that when you update them, git history basically increase by 80MB. 

If you say so, then I guess moving on from previous "drop yourself files here" was really important for you.. So I guess I'll have to find a way to *also* make me happy 😃  #12

**Pull request closed without merging**
